const IS_MAINNET = true;
const IS_INTERNAL_MAINNET = false;

const MAX_THRESHOLD_FOR_SWAP = '30000';
const PATH_FINDER_ENDPOINT = 'https://api.pathfinder.routerprotocol.com/api';
const DEFAULT_SOURCE_NETWORK_ID = '137';
const DEFAULT_DESTINATION_NETWORK_ID = '56';
const ALLOWED_CHAINS = '137,56,43114,250,10,1,42161,1666600000,1313161554,25';
const ROUTER_STATS_HOST = 'https://api.stats.routerprotocol.com';

module.exports = {
  IS_MAINNET,
  MAX_THRESHOLD_FOR_SWAP,
  PATH_FINDER_ENDPOINT,
  DEFAULT_SOURCE_NETWORK_ID,
  DEFAULT_DESTINATION_NETWORK_ID,
  ALLOWED_CHAINS,
  ROUTER_STATS_HOST,
  IS_INTERNAL_MAINNET
};